FIPs 36-40
fioprotocol/fio.devtools pull request #61
Opened 2022-07-26 20:03 UTC by edrotthoff

FIP-38 add new action and fee 

further details will be added as development continues.

2023-01-20 22:25 UTC, ericbutz requested changes

2023-01-20 22:25 UTC, ericbutz commented on scripts/launch/07_create_zero_fees.sh
> +./clio -u http://localhost:8879 push action fio.fee createfee '{"end_point":"new_fio_chain_account","type":"0","suf_amount":"0"}' --permission fio.fee@active
depends on whether we change this to new_fio_account

2023-01-20 22:25 UTC, ericbutz commented on scripts/launch/18_create_set_fees_after_genesis.sh
> +./clio -u http://localhost:8879 push action -f fio.fee createfee '{"end_point":"new_fio_chain_account","type":"0","suf_amount":"2000000000"}' --permission fio.fee@active
Confirm name before merge.

2023-01-26 00:23 UTC, adsorptionenthalpy approved these changes

2023-02-06 21:57 UTC, ericbutz approved these changes

2023-02-06 21:57 UTC, merged